### ISSUE TITLE
Version 1.0 To-Do

### ISSUE THREAD

**Issue by ofelizestevez** [ofelizestevez/bookQuest#1]
- [ ] Planning
- [ ] #2
- [ ] Authentication Functionality
- [ ] CI/CD
  - [ ] Integration Testing
  - [ ] Deployment
- [ ] Monitoring
- [ ] Logging
- [ ] Book Search Functionality
- [ ] User Library Functionality
- [ ] Implement Different Environments
- [ ] Implement Backup for Production Environment
- [ ] Implement Docker Swarm w/ Auto Scaling
